import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { config } from "dotenv";
config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function startServer() {
 const app = express();
  const PORT = process.env.PORT || 3000;

  app.use(express.json({ limit: "50mb" }));
  // CORS middleware
  app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type, Authorization");
    if (req.method === "OPTIONS") {
      return res.sendStatus(200);
    }
    next();
  });


  // API proxy route for Nvidia
  app.post("/api/proxy/nvidia", async (req, res) => {
    try {
      const { url, headers, body } = req.body;
      const apiRes = await fetch(url, {
        method: "POST",
        headers: headers,
        body: JSON.stringify(body)
      });
      const text = await apiRes.text();
      let data;
      try {
        data = JSON.parse(text);
      } catch(e) {
        data = { message: text };
      }
      res.status(apiRes.status).json(data);
    } catch (error) {
      console.error("Nvidia proxy error:", error);
      res.status(500).json({ error: error.message, message: error.message });
    }
  });

  // API route for local Depth Anything V2 model processing
  app.post("/api/depth-map", async (req, res) => {
    const { writeFileSync, unlinkSync, existsSync, readFileSync } = await import("fs");
    const { exec } = await import("child_process");
    
    try {
      const { image, modelPath } = req.body;
      if (!image) {
        return res.status(400).json({ error: "Missing image data" });
      }

      const defaultModel = path.join(__dirname, "models", "depth_anything_v2_vitl.pth");
      const activeModelPath = modelPath && modelPath !== "/models/depth_anything_v2_vitl.pth" ? modelPath : defaultModel;
      
      if (!existsSync(activeModelPath)) {
        return res.status(400).json({ error: "未找到深度估计模型文件: " + activeModelPath });
      }

      let base64Data = image;
      if (image.includes("base64,")) {
        base64Data = image.split("base64,")[1];
      }
      
      const buffer = Buffer.from(base64Data, "base64");
      const tempId = Date.now() + "_" + Math.floor(Math.random() * 1000);
      const tempInputPath = path.join(__dirname, `temp_input_${tempId}.jpg`);
      const tempOutputPath = path.join(__dirname, `temp_output_${tempId}.png`);
      
      writeFileSync(tempInputPath, buffer);
      
      const cmd = `C:\\Users\\sa\\Documents\\lexicona\\gpu_env\\Scripts\\python.exe run_depth_anything.py --image "${tempInputPath}" --model "${activeModelPath}" --output "${tempOutputPath}"`;
      console.log("Executing depth map command:", cmd);
      
      await new Promise((resolve, reject) => {
        exec(cmd, (error, stdout, stderr) => {
          if (error) {
            console.error("Python depth error:", error.message);
            return reject(new Error(stderr || error.message || 'Python script failed'));
          }
          console.log("Python stdout:", stdout);
          resolve();
        });
      });
      
      if (!existsSync(tempOutputPath)) {
        throw new Error("Output depth map image was not generated by script");
      }
      
      const outputBuffer = readFileSync(tempOutputPath);
      const outputBase64 = "data:image/png;base64," + outputBuffer.toString("base64");
      
      try {
        if (existsSync(tempInputPath)) unlinkSync(tempInputPath);
        if (existsSync(tempOutputPath)) unlinkSync(tempOutputPath);
      } catch (err) {
        console.error("Failed to delete temp files", err);
      }
      
      res.json({ success: true, depthMapUrl: outputBase64 });
    } catch (error) {
      console.error("Depth map generation failed:", error);
      res.status(500).json({ error: error.message || "Internal error during depth map generation" });
    }
  });

  // Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  app.listen(PORT, "0.0.0.0", () => {
    console.log("API server running on http://0.0.0.0:" + PORT);
  });
}

startServer();
