import express from "express";
import path from "path";
import { existsSync } from "fs";

function findProjectRoot(): string {
  const markers = ["gpu_env", "models", "depth-anything-v2", "run_depth_anything.py"];
  const candidates = [process.cwd()];
  try {
    const exeDir = path.dirname(process.execPath);
    candidates.push(path.resolve(exeDir, "..", ".."));
  } catch (_) {}
  for (const candidate of candidates) {
    if (markers.some((m) => existsSync(path.join(candidate, m)))) return candidate;
  }
  return process.cwd();
}
const ROOT = process.env.LEXICONA_ROOT || findProjectRoot();

async function startServer() {
  const app = express();
  const PORT = parseInt(process.env.PORT || "3000");

  app.use(express.json({ limit: "50mb" }));
  
  // CORS middleware
  app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Content-Type, Authorization");
    if (req.method === "OPTIONS") {
      return res.sendStatus(200);
    }
    next();
  });

  // API proxy route for Nvidia
  app.post("/api/proxy/nvidia", async (req, res) => {
    try {
      const { url, headers, body } = req.body;
      const apiRes = await fetch(url, {
        method: "POST",
        headers: headers,
        body: JSON.stringify(body)
      });
      const text = await apiRes.text();
      let data;
      try {
        data = JSON.parse(text);
      } catch(e) {
        data = { message: text };
      }
      res.status(apiRes.status).json(data);
    } catch (error: any) {
      console.error("Nvidia proxy error:", error);
      res.status(500).json({ error: error.message, message: error.message });
    }
  });

  // API route for local Depth Anything V2 model processing
  app.post("/api/depth-map", async (req, res) => {
    const { writeFileSync, unlinkSync, existsSync, readFileSync } = await import("fs");
    const { exec } = await import("child_process");
    
    try {
      const { image, modelPath } = req.body;
      if (!image) {
        return res.status(400).json({ error: "Missing image data" });
      }

      const defaultModel = modelPath && modelPath !== "/models/depth_anything_v2_vitl.pth" ? modelPath : path.join(ROOT, "models", "depth_anything_v2_vitl.pth");
      const activeModelPath = defaultModel;
      if (!existsSync(activeModelPath)) {
        return res.status(400).json({ error: "未找到深度估计模型文件: " + activeModelPath });
      }
      
      // Clean up base64 prefix
      let base64Data = image;
      if (image.includes("base64,")) {
        base64Data = image.split("base64,")[1];
      }
      
      const buffer = Buffer.from(base64Data, "base64");
      const tempId = Date.now() + "_" + Math.floor(Math.random() * 1000);
      const tempInputPath = path.join(ROOT, `temp_input_${tempId}.jpg`);
      const tempOutputPath = path.join(ROOT, `temp_output_${tempId}.png`);
      
      writeFileSync(tempInputPath, buffer);
      
      // Run the Python script
      const pythonPath = path.join(ROOT, "gpu_env", "Scripts", "python.exe");
      const scriptPath = path.join(ROOT, "run_depth_anything.py");
      const cmd = `"${pythonPath}" "${scriptPath}" --image "${tempInputPath}" --model "${activeModelPath}" --output "${tempOutputPath}"`;
      console.log(`Executing depth map command: ${cmd}`);
      
      await new Promise<void>((resolve, reject) => {
        exec(cmd, (error, stdout, stderr) => {
          if (error) {
            console.error(`Python depth execution error: ${error.message}. Stderr: ${stderr}`);
            return reject(new Error(error.message || "Python script failed"));
          }
          console.log(`Python stdout: ${stdout}`);
          resolve();
        });
      });
      
      if (!existsSync(tempOutputPath)) {
        throw new Error("Output depth map image was not generated by script");
      }
      
      // Read output image and convert back to base64
      const outputBuffer = readFileSync(tempOutputPath);
      const outputBase64 = `data:image/png;base64,${outputBuffer.toString("base64")}`;
      
      // Clean up temp files
      try {
        if (existsSync(tempInputPath)) unlinkSync(tempInputPath);
        if (existsSync(tempOutputPath)) unlinkSync(tempOutputPath);
      } catch (err) {
        console.error("Failed to delete temp files", err);
      }
      
      res.json({ success: true, depthMapUrl: outputBase64 });
    } catch (error: any) {
      console.error("Depth map generation failed:", error);
      res.status(500).json({ error: error.message || "Internal error during depth map generation" });
    }
  });

  // API route to download offline HTML directly
  app.get("/api/download-offline", async (req, res) => {
    const { existsSync } = await import("fs");
    const { exec } = await import("child_process");
    const offlinePathDist = path.join(ROOT, "dist", "PromptEagle_Offline.html");
    const offlinePathPublic = path.join(ROOT, "public", "PromptEagle_Offline.html");
    
    // In development, or if file is missing, build it dynamically
    if (process.env.NODE_ENV !== "production" || (!existsSync(offlinePathDist) && !existsSync(offlinePathPublic))) {
      try {
        console.log("Generating offline compilation...");
        await new Promise((resolve, reject) => {
          exec("npm run build", (error, stdout, stderr) => {
            if (error) {
              console.error("Build failed:", error);
              return reject(error);
            }
            resolve(stdout);
          });
        });
      } catch (err: any) {
        return res.status(500).send("构建离线文件失败，请查看云端日志：" + err.message);
      }
    }

    if (existsSync(offlinePathDist)) {
      res.download(offlinePathDist, "Lexicona-Offline.html");
    } else if (existsSync(offlinePathPublic)) {
      res.download(offlinePathPublic, "Lexicona-Offline.html");
    } else {
      res.status(404).send("离线版文件尚未生成！请先在网页加载后运行 npm run build 构建。");
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
} else {
   const distPath = process.env.LEXICONA_DIST || path.join(ROOT, "dist");
    app.get("*", (req, res) => {
      const { readFileSync, existsSync } = require("fs");
      let filePath = path.join(distPath, req.path === "/" ? "index.html" : req.path.substring(1));
      try {
        if (existsSync(filePath)) {
          const content = readFileSync(filePath);
          const mime = {".html":"text/html",".js":"application/javascript",".css":"text/css",".png":"image/png",".jpg":"image/jpeg",".svg":"image/svg+xml",".ico":"image/x-icon",".json":"application/json",".woff":"font/woff",".woff2":"font/woff2",".ttf":"font/ttf",".map":"application/json"};
          res.set("Content-Type", mime[path.extname(filePath).toLowerCase()] || "application/octet-stream");
          res.send(content);
        } else {
          filePath = path.join(distPath, "index.html");
          if (existsSync(filePath)) {
            res.set("Content-Type", "text/html");
            res.send(readFileSync(filePath));
          } else {
            res.status(404).send("Not Found");
          }
        }
      } catch (e) {
        res.status(500).send("Server Error");
      }
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
